name: Deploy to Streamlit

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Streamlit Cloud
        run: |
          echo "🚀 Deploying to Streamlit Cloud..."
          echo "App will be available at: https://challenge-ci-cd-app-kwkjvhjrcidvbgvsarrr9e.streamlit.app/"
