name: CI
run-name: CI 🚀

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint with Docker
        run: |
          docker run --rm -v $(pwd):/app -w /app python:3.12-slim bash -c '
            pip install flake8 &&
            flake8 app tests --max-line-length=2000
          '

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with Docker
        run: |
          docker run --rm -v $(pwd):/app -w /app python:3.12-slim bash -c '
            pip install -r requirements.txt &&
            pip install -e . &&
            if [ -f "tests/test_app.py" ]; then
              python -m pytest tests/ -v --tb=short
            else
              echo "No tests found, skipping"
            fi
          '
