name: Auto PR

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Check if branch has changes
        id: changes
        run: |
          if git diff --quiet origin/main...HEAD; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: "Auto PR: ${{ github.ref_name }} → main"
          body: "Auto PR from branch `${{ github.ref_name }}`"
          base: main
