name: Auto PR

on:
  push:
    branches:
      - " * "

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' # Don't run on main branch
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-update"
          branch: auto-pr-branch
          title: "Auto PR from main branch"
          body: "This PR was automatically created from any branches commits."
