name: Auto PR

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Create Pull Request
        run: |
          gh pr create \
            --title "Auto PR: ${{ github.ref_name }} → main" \
            --body "Auto PR from branch \`${{ github.ref_name }}\`" \
            --base main \
            --head ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
